name: Publish GitHub Pages

on:
  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install Sphinx
      run: |
        pip install -U sphinx
    - name: Build HTML pages
      run: make html
#  deploy:
#    permissions:
#      contents: read
#      pages: write
#      id-token: write
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
